services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: directloc
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
